### PR TITLE
feat(wizard_router): allow the user to complete the wizard flow

### PR DESCRIPTION
**Pull request by sappo**

### CODE REVIEW

**Comment by spydon** [comment]
@sappo could you sign the CLA? Then we can merge this :)

**Review by spydon — APPROVED** [review]

**Comment by sappo** [comment]
Just did for the 2nd time, but the check is still failing

**Comment by spydon** [comment]
> Just did for the 2nd time, but the check is still failing

Ah, it's due to that you don't have a default e-mail connected to the actions you take through the web interface I think, so your merges for example are connected with this e-mail: `sappo@users.noreply.github.com`

What you could do is just squash everything down to one commit that is up to date with the latest on `main`, or change the e-mail of the commits with the faulty e-mail to the e-mail that you signed the CLA with.

**Comment by spydon** [comment]
There, I fixed it for you @sappo :)

**Review by spydon — APPROVED** [review]

**Comment by sappo** [comment]
@spydon thanks 👍

**Pull request merged**
