### PR TITLE
docs: Improved pubspec file for pub.dev and fixed GitHub project URL

### PR DESCRIPTION
**Pull request by lsaudon**
Hi everyone,

I noticed that the link on pub.dev was no longer the right one.

I've also added the link for issues and added the topic lints

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm, thanks for your contribution

**Comment by lsaudon** [comment]
Failed actions have anything to do with my pull request except `PR/cla`.
For cla, I don't know what to wear for this:
- Please add the Canonical Project Manager or contact

**Comment by spydon** [comment]
> Failed actions have anything to do with my pull request except `PR/cla`.
> For cla, I don't know what to wear for this:
> - Please add the Canonical Project Manager or contact

It's a problem with launchpad, it'll hopefully be back soon.

**Comment by spydon** [comment]
@lsaudon unfortunately they are still having problems with the CLA for first-time contributors, I'll make sure to re-run it once it is fixed.

**Comment by spydon** [comment]
@lsaudon it seems like you haven't actually properly signed the CLA (because now it should work), you can write my name in the contact field.

**Comment by lsaudon** [comment]
I write your name in the contact field.

Nice first name, by the way 😄.

**Comment by lsaudon** [comment]
Why merging is blocked ?

**Comment by spydon** [comment]
> Why merging is blocked ?

No idea... I'll have a look on Monday

**Pull request merged**
