### PR TITLE
Add stock labels

### PR DESCRIPTION
**Pull request by jpnurmi**
For sharing translations between Ubuntu apps.

### CODE REVIEW

**Comment by jpnurmi** [comment]
P.S. I'm feeling a bit unsure if this is a good idea before we have some sort of support for mnemonics in Flutter.

**Comment by jpnurmi** [comment]
I discussed this with our a11y experts a while back and they didn't see mnemonics as important. Apparently, Apple deprecated mnemonics 10 years ago.

**Comment by jpnurmi** [comment]
@Feichtmeier What do you think, would it be useful to collectively translate and share this kind of "stock" labels for Ubuntu Flutter apps to avoid every app needing to translate them again and again?

You'd use it similarly to `MaterialLocalizations` from `flutter_localizations`:

```yaml
# pubspec.yaml
ubuntu_localizations: ...
```

```dart
import 'package:ubuntu_localizations/ubuntu_localizations.dart';
```

```dart
MaterialApp(
  localizationsDelegates: [
    ...AppLocalizations.localizationsDelegates,
    ...GlobalUbuntuLocalizations.delegates,
  ],
  supportedLocales: AppLocalizations.supportedLocales,
)
```

```dart
Text(
  UbuntuLocalizations.of(context).quitLabel
),
```

**Comment by Feichtmeier** [comment]
Good idea! Ah so you can use different delegates! Nice idea

**Comment by Feichtmeier** [comment]
I will definitively also add those that fit here from the Software app

**Review by d-loose — APPROVED** [review]
LGTM :+1:  (although I must admit that I didn't check all 22,602 added lines :upside_down_face: )

**Comment by jpnurmi** [comment]
Only the first file/commit is relevant. :)

P.S. Is there a way we could leave the generated files out? As far as I know, the usual `generate: true` and `package:flutter_gen/gen_l10n/foo_localizations.dart` approach only works for app localizations.

**Comment by d-loose** [comment]
I don't know, but I'm definitely in favor of keeping track of as few as possible generated files in the repo :)

**Comment by jpnurmi** [comment]
I tried deleting the generated files and applying these changes to generate them on the fly:

```diff
diff --git a/packages/ubuntu_localizations/l10n.yaml b/packages/ubuntu_localizations/l10n.yaml
index 1a06eb5..83906bc 100644
--- a/packages/ubuntu_localizations/l10n.yaml
+++ b/packages/ubuntu_localizations/l10n.yaml
@@ -2,5 +2,4 @@ arb-dir: lib/src/l10n
 template-arb-file: ubuntu_en.arb
 output-class: UbuntuLocalizations
 output-localization-file: ubuntu_localizations.dart
-synthetic-package: false
 nullable-getter: false
diff --git a/packages/ubuntu_localizations/lib/src/localizations.dart b/packages/ubuntu_localizations/lib/src/localizations.dart
index 82325c5..4d6a87e 100644
--- a/packages/ubuntu_localizations/lib/src/localizations.dart
+++ b/packages/ubuntu_localizations/lib/src/localizations.dart
@@ -3,10 +3,10 @@ import 'package:flutter/material.dart';
 import 'package:intl/intl.dart';
 import 'package:intl/intl_standalone.dart';
 
-import 'l10n/ubuntu_localizations.dart';
+import 'package:flutter_gen/gen_l10n/ubuntu_localizations.dart';
 import 'material/material_localizations.dart';
 
-export 'l10n/ubuntu_localizations.dart';
+export 'package:flutter_gen/gen_l10n/ubuntu_localizations.dart';
 
 /// Provides localization delegates.
 class GlobalUbuntuLocalizations {
diff --git a/packages/ubuntu_localizations/pubspec.yaml b/packages/ubuntu_localizations/pubspec.yaml
index 10469d6..9626aa3 100644
--- a/packages/ubuntu_localizations/pubspec.yaml
+++ b/packages/ubuntu_localizations/pubspec.yaml
@@ -23,3 +23,6 @@ dev_dependencies:
   flutter_test:
     sdk: flutter
   xml: ^6.1.0
+
+flutter:
+  generate: true
```

This works for the library package itself in the sense that it's able to find the generated files in `.dart_tool/flutter_gen/gen_l10n` after running `pub get` or `gen-l10n` for the library.

However, when you add the package as a dependency for an app, it cannot resolve such files. The app only generates its own `app_localizations*.dart` and there's no sign of `ubuntu_localizations*.dart`. Supposedly, library dependencies have to be complete and cannot generate stuff on the fly. I think this is why the generated files had to be checked in for this package. :(

```
ERROR: import 'package:flutter_gen/gen_l10n/ubuntu_localizations.dart';
```

**Pull request merged**
