### PR TITLE
feat: wizard_router add previous

### LINKED ISSUE #432: wizard_router : back function does not load previous route in routes if not already loaded in state.
## Steps to reproduce :
- load wizard_router with 3 routes : 'route1', 'route2', 'route3'.  => 'route1' is loaded
- call `jump('route3')` => 'route3' is loaded
- call `back()` => 'route1' is loaded and not 'route2'

## code exploration : 
back function search for previous route in routes. If the previous route is not found in state, `state.lastIndexWhere((settings) => settings.name == previous)` returns -1 and the route at index 0 of state is loaded.

## Solution proposition :
if route is not in state, call `_loadRoute` and place it before current route in state.

I can try to resolve it with a PR if you think it's a good solution.

### PR DESCRIPTION
**Pull request by WilliamMrc**
add a previous function ro resolve #432

### CODE REVIEW

**Comment by WilliamMrc** [comment]
codecov/project job is not comparing to the latest commit in main and shows changes that are not in this PR. Is there something I can do to resolve it ?

**Comment by spydon** [comment]
> codecov/project job is not comparing to the latest commit in main and shows changes that are not in this PR. Is there something I can do to resolve it ?

Don't worry about that one, it's not a required one (and it doesn't work like it should atm).

**Review by spydon — APPROVED** [review]

**Comment by spydon** [comment]
@WilliamMrc all commits need to be signed for us to be able to merge this:
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
You can sign them retrospectively.

**Comment by WilliamMrc** [comment]
hi @spydon, thanks for the feed back.
I would like your help about signature.
I have setup the gpg key and am able to sign my commits but if I rebase the branch to edit my commits, I mess up with the two merge commits you did. is there something I am missing ?

**Comment by spydon** [comment]
> hi @spydon, thanks for the feed back.
> I would like your help about signature.
> I have setup the gpg key and am able to sign my commits but if I rebase the branch to edit my commits, I mess up with the two merge commits you did. is there something I am missing ?

You should be able to pull first and then rebase with -i, something like this:
https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/contributors/signing-commits.html

**Comment by spydon** [comment]
@WilliamMrc this feature is now included in wizard_router v1.4.0

**Pull request merged**
