### PR TITLE
feat: providing an optional render when an icon fails to resolve entirely

### PR DESCRIPTION
**Pull request by mattkae**
## What's new?
- If an icon fails to resolve, the caller can provide an option render function to use in its place

## Motivation
We might want to show some sort of nice "Icon not found" icon when it is unavailable on a system for any reason.

## Example usage
```dart
return XdgIcon(
        name: iconName,
        size: size,
        iconNotFoundBuilder: () {
          return SizedBox(
              width: size.toDouble(),
              height: size.toDouble(),
              child: Center(
                  child: Text(
                      iconName.isEmpty ? "U" : iconName[0].toUpperCase(),
                      style: Theme.of(context).textTheme.displayLarge)));
        });
```

### CODE REVIEW

**Comment by mattkae** [comment]
Note that the introduction of the new `_iconNotFound` boolean is to distinguish between the initial "loading" case and the "failure to resolve" case. Perhaps we would be better off with an `initialLoading` flag instead, but let me know

**Review by spydon — APPROVED** [review]
A little bit less readable in `_updateIcon`, but I think that it's acceptable.
Where are you going to use this if I may ask? :)

**Comment by spydon** [comment]
@mattkae all commits need to be signed before this can be merged.

**Comment by mattkae** [comment]
Eh hold on, I'll reopen this, since I think I did the wrong force push ;)

**Pull request closed without merging**
